services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    restart: always

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    restart: always